---
name: Docker

"on":
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: githublint
  BUILD_OPTS: --target stage-prd --file Dockerfile

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: sudo npm install -g bats

      - name: Run tests
        run: |
          docker run --rm -e GITHUB_TOKEN \
            -v "$PWD:/home/curl_user/project" \
            -w "/home/curl_user/project" \
            -u curl_user \
            "$(docker build . -q --target stage-dev --file Dockerfile)" \
            bats --tap test

          docker build . $BUILD_OPTS

          bats --tap test/integration.bats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          VERSION=''
          [[ "${GITHUB_REF}" != "refs/tags/v"* ]] || VERSION="${GITHUB_REF##*/v}"

          docker build . $BUILD_OPTS --tag "$IMAGE_NAME" --build-arg VERSION="$VERSION"

      - name: Log into registry
        run: echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u "$GITHUB_ACTOR" --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: |
          # Change all uppercase to lowercase
          IMAGE_ID="docker.pkg.github.com/${GITHUB_REPOSITORY,,}/${IMAGE_NAME,,}"

          # Strip git ref prefix from version
          VERSION="${GITHUB_REF##*/}"

          # Strip "v" prefix from tag name
          [[ "${GITHUB_REF}" != "refs/tags/"* ]] || VERSION=${VERSION#v}

          # Use Docker `latest` tag convention
          [ "$VERSION" != "main" ] || VERSION=latest

          echo "IMAGE_ID=$IMAGE_ID"
          echo "VERSION=$VERSION"

          docker tag "$IMAGE_NAME" "$IMAGE_ID:$VERSION"
          docker push "$IMAGE_ID:$VERSION"
